### ISSUE TITLE
Change Request: replace react-native-fast-image by expo-image

### ISSUE THREAD

**Issue by jeremyspritelyco** [dev-yakuza/react-native-image-modal#216]

**Comment by fukemy** [comment]
expo-image now better than fast-image, but it's require expo-native-module and hard guild to install success, like pain of ass

**Comment by dev-yakuza** [comment]
@jeremyspritelyco @fukemy I'm not sure that you still use this library.

I refactored removing the dependency of `react-native-fast-image` add add the `renderImageComponent` props like the following link.

- https://github.com/dev-yakuza/react-native-image-modal/blob/main/Example/src/ExternalLibrary/index.tsx

So, if you want to use external library like `react-native-fast-image` or `expo-image` instead of the `Image` component, try to use the `renderImageComponent` props`.

I close this issue. If you have any trouble with it, please let me know it.
