### ISSUE TITLE
[2787,"RCTView",1,{"renderToHardwareTextureAndroid":true,"left":"<<NaN>>","top":"<<NaN>>","width":"<<NaN>>","height":"<<NaN>>","transform":[{"scale":1},{"translateX":0},{"translateY":0}]}] is not usable as a native method argument

### ISSUE THREAD

**Issue by zlep** [dev-yakuza/react-native-image-modal#5]
[2787,"RCTView",1,{"renderToHardwareTextureAndroid":true,"left":"<<NaN>>","top":"<<NaN>>","width":"<<NaN>>","height":"<<NaN>>","transform":[{"scale":1},{"translateX":0},{"translateY":0}]}] is not usable as a native method argument

Crashes on android (simulator only?).

**Comment by dev-yakuza** [comment]
@zlep

can you explain your situation more?

1. only crashed on an Android device? the emulator is OK?
2. could you test with Example project in this repository?
3. can you share your source code?

thanks.

**Comment by zlep** [comment]
1.) It crashes on Android simulator. Unfortunately I don't have a real Android device to test.
iOS is working, both, simulator and real device.

2.) same behaviour 

3.) I removed it for now, sorry, but it was nothing special, just like this:

`<View style={MainStyles.productImageContainer}>
        <View
          style={{ backgroundColor: Colors.grey_1, width: 150, height: 150 }}
        >
          <ImageModal
            resizeMode="contain"
            style={{
              width: 150,
              height: 150
            }}
            source={{
              uri: `URL/${image}`
            }}
          />
        </View>
      </View>`

**Comment by dev-yakuza** [comment]
@zlep 

thanks for replying.

I also tested on Android emulator and device after your report.
however, I didn't find any problem.

my version info is like below.

```
node: v13.8.0

android device: 5.1.1
android emulator: 10

react: 16.9.0,
react-native: 0.61.5,
react-native-image-modal: 1.0.1
```

can you share your version info?

thanks!

**Comment by zlep** [comment]
Thanks. I reinstalled the package and wiped the data of the android simulator. It seems to be working now. Strange.

Edit: The only thing I notice is a little laggy closing animation on android. iOS is smooth.

**Comment by dev-yakuza** [comment]
@zlep it's great news!

sorry, I am not helpful...but you solve it! great!

a little laggy closing animation on android because of the emulator, I think.
If you test it on Android device, you can see smooth animation like iOS.
I close this issue. If you have still laggy animation on Android device, please make another issue.

thanks!

**Comment by dev-yakuza** [comment]
@zlep it's great news!

sorry, I am not helpful...but you solve it! great!

a little laggy closing animation on android because of the emulator, I think.
If you test it on Android device, you can see smooth animation like iOS.
I close this issue. If you have still laggy animation on Android device, please make another issue.

thanks!
