### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name FastImageView

### ISSUE THREAD

**Issue by yawijaya96** [dev-yakuza/react-native-image-modal#59]
Hello, 

- ERROR  Invariant Violation: Tried to register two views with the same name FastImageView
- ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
- ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

i have installed fastimage package with latest version,
and then today i try this package, starting metro as usual and it goes to error

**Comment by dev-yakuza** [comment]
@yudhaaw96 

Thanks for reporting.
However, I can't investigate this issue. So, could you give me more details? (e.g. sample code, details about the situation, how to make the same error)

Thanks.

**Comment by dbotman** [comment]
I get the same error:

**ERROR**    Invariant Violation: Tried to register two views with the same name FastImageView

Does anyone have a solution yet?

react-native-image-modal@2.0.3
react-native-fast-image@8.3.7
expo@40.0.1
react-native@0.63.4
react@16.13.1

It seems to happen after the upgrade from Expo 39 to Expo 40

**Comment by dev-yakuza** [comment]
@dbotman 
> This library does not support Expo anymore. Because this library uses `react-native-fast-image`.

Please check the `README`.

- https://github.com/dev-yakuza/react-native-image-modal#expo

![Screen Shot 2021-08-30 at 21 39 50](https://user-images.githubusercontent.com/42969906/131340526-e99b4cbb-932e-41ab-8b2e-04f00ea460a1.jpg)

**Comment by naheed-shamim** [comment]
Try installing react-native-fast-image@8.3.4

**Comment by yawijaya96** [comment]
downgrading to version 1.0.16 works for me, no more "Invariant Violation: Tried to register two views with the same name FastImageView"

**Comment by andreialecu** [comment]
Ran into the same issue.


The problem here is that this package defined `react-native-fast-image` as a dependency but it should be in `peerDependencies` instead.

Ref: https://github.com/dev-yakuza/react-native-image-modal/blob/62e93f53558a9d6e08c444dedb86177e03c225be/package.json#L69-L71

The technical reason this happens is because `yarn` may install `react-native-fast-image` twice on two separate versions.

```
➜ yarn why react-native-fast-image        
├─ x@workspace:.
│  └─ react-native-fast-image@npm:8.3.7 [ceb3f] (via npm:^8.3.2 [ceb3f])
│
├─ react-native-image-modal@npm:2.0.3
│  └─ react-native-fast-image@npm:8.3.4 (via npm:8.3.4)
│
└─ react-native-image-modal@npm:2.0.3 [ceb3f]
   └─ react-native-fast-image@npm:8.3.4 [74cfa] (via npm:8.3.4 [74cfa])
```


Notice how both 8.3.7 and 8.3.4 are installed.

The correct way to fix this would be to make it a peer dependency however. The installation guide mentions it needs to be installed in the parent project anyways: https://github.com/dev-yakuza/react-native-image-modal#installation

I'll open a PR shortly with a fix.
